### PR TITLE
TemplateFetcher interface

### PR DESCRIPTION
**Pull request by braceta**
Hi,

First of all thank you for this great module. 

We had some specific requirements for using templates, which will require to fetch templates not from filesystem but instead using go-bindata or Cassandra. 

For that purpose this PR adds a TemplateFetcher interface that allows delegation of template fetching.

Would you like these changes in upstream?

Thank you

### CODE REVIEW

**Comment by linniksa** [comment]
:+1:

**Comment by flosch** [comment]
Thanks for your pull request. This kind of issue is already on my agenda and I'm actively developing such a feature; please see issue #68. I will check your PR for further inspirations.

**Comment by interlock** [comment]
@braceta I just noticed this PR solves a similar problem that I put a PR #88 into earlier this week. We may be able to merge some of the changes from both PR's.

**Comment by flosch** [comment]
I guess this PR is obsolete now since I've implemented virtual filesystem capabilities. Thanks anyway for your effort!

**Pull request closed without merging**
