### PR TITLE
Implemented jinja-like whitespace control

### PR DESCRIPTION
**Pull request by spuzirev**
https://github.com/flosch/pongo2/issues/168

### CODE REVIEW

**Comment by gavbaa** [comment]
Could you please add a few tests demonstrating the functionality as well?

**Comment by spuzirev** [comment]
@gavbaa , take a look.

**Comment by spuzirev** [comment]
@gavbaa , ping

**Comment by gavbaa** [comment]
This looks very similar to Jinja's whitespace logic, and the tests look reasonable.  I can't merge myself, but it's a workable PR to me.  This assumes that @flosch is looking to offer an "extended" mode that exceeds standard Django syntax.

**Comment by excavador** [comment]
@gavbaa @flosch any updates?

**Comment by flosch** [comment]
Thanks!

**Pull request merged**
