### PR TITLE
Nil pointer reference panic avoided

### PR DESCRIPTION
**Pull request by velanse**
Eliminating panic when sending a variable with a nil pointer reference in include tag and then trying to access param or function on this variable.

Example
```
{% include "includes.helper" with my_var=some_undefined_var %}
```
in includes.helper:
```
{% if my_var.param %}I will panic since my_var is actually a nil pointer.{% endif %}
```

### CODE REVIEW

**Comment by kihamo** [comment]
+1

**Comment by flosch** [comment]
Can you please include a test case for this kind of error? Thank you!

**Comment by velanse** [comment]
Thank you for your feedback. Sure - just added this test case.

**Comment by flosch** [comment]
I'm still not sure whether we should simply ignore these kind of errors since I'm doing the same when you're trying to access a not existing variable (printing out nothing in such situations).

**Comment by velanse** [comment]
Got you. Updated this fix.

**Comment by flosch** [comment]
Thanks!

**Pull request merged**
