### PR TITLE
add time.Time support to Value and comparison operators

### LINKED ISSUE #231: time.Time comparison
Hello !
I plan to add `time.Time` comparison support.
Is it OK for you ?

### PR DESCRIPTION
**Pull request by pierrre**
Fixes #231

### CODE REVIEW

**Comment by pierrre** [comment]
Do you agree with the way I'm planning to add `time.TIme` support ?
Do you prefer to do it in another way ?

I will add tests in this PR if the way it's done is OK for you.

**Comment by pierrre** [comment]
For now I'm not planning to add implicit type conversion, like in the `Integer()` method.
I don't need it currently, and I don't know yet what would be the good approach (return the timestamp in second or nansecond ?)

**Comment by pierrre** [comment]
I've added tests for time comparison.

**Comment by flosch** [comment]
Thanks for adding tests. Reviewing now.

**Pull request merged**
