### PR TITLE
Add a way to globally disable autoescape

### PR DESCRIPTION
**Pull request by siemin93**
Hi,

I'm using pongo2 backend side and I'm working a lot with URLs etc. So basically I want to have autoescape disabled all the time. How about such a simple change?

### CODE REVIEW

**Comment by pamelin** [comment]
We need similar functionality to set autoescape default to false.

Is there a reason why this can not be merged?

The only difference I would suggest is to pass it in the context rather than have it as a variable however the suggested solution works for us

**Comment by pamelin** [comment]
Can this be merged?

**Comment by pamelin** [comment]
Hey @flosch we need similar feature and we are wondering if this will be merged? Otherwise we will have to find our own solution.

**Comment by fooksca** [comment]
Hi @flosch, this would be great for me too. I'm using pongo2 (which is great, btw) outside an HTML context, and would appreciate this. I'm currently decorating pongo2 to wrap all my templates in `{% autoescape off %}` and `{% endautoescape %}`, so it's not much hassle, but would love to delete this from my code …

**Comment by gavbaa** [comment]
@siemin93 , could you please separate your pull requests so that the divide by zero fix is in its own pull?

**Comment by flosch** [comment]
@siemin93 can you please move div by zero to another PR, then we can merge this.

**Pull request merged**
