### PR TITLE
Remove dependency on github.com/juju/errors

### PR DESCRIPTION
**Pull request by jclc**
#223

### CODE REVIEW

**Comment by kataras** [comment]
That dependency was the whole reason I had to fork this repository at Dec 12, 2019 and change the import path for [Iris](https://github.com/kataras/iris) users... This is fixed now so we can get back on using this package directly.

**Comment by jclc** [comment]
Why.... didn't you just make a pull request here?

**Comment by kataras** [comment]
Because @jclc I saw the latest release was 6 years ago...and you know, I can't wait others to fix my users' issues.. I take action fast. For example, we certain need a **new release** and even a new import path for `github.com/flosch/pongo2/v4`...

**Comment by kataras** [comment]
Because @jclc I saw the latest release was 6 years ago and it has 7 open pull requests already, not yet merged for months (and years)...and you know, I can't wait others to fix my users' issues.. I take action fast. For example, we certain need a **new release** and even a new import path for `github.com/flosch/pongo2/v4`. I can do it in 5 minutes, will you accept my PR?

**Comment by kataras** [comment]
The https://github.com/flosch/pongo2-addons needs to be a go module as well, it does not contain a release or a tag so it can be `v0.0.1` with a simple `go.mod` of `module github.com/flosch/pongo2-addons`. Is there a chance to make me a contributor to both of the packages so I can upgrade and probably maintain their status on future needs?

**Comment by kataras** [comment]
Also,  the current pongo2's `go.mod` contains https://github.com/flosch/pongo2/blob/5abacdfa4915f8afb6de6231455488066273bea6/go.mod#L6-L8 

But `github.com/go-check/check` == `gopkg.in/check.v1` ...

**Pull request merged**
