### PR TITLE
Adds support for negative to bound in slice filter

### PR DESCRIPTION
**Pull request by gbts**
Related to issue #263, I ended up using a custom filter in my own template that just adds an extra branch in filterSlice to calculate & check the negative to bound

### CODE REVIEW

**Comment by flosch** [comment]
Thanks for your PR. Can you please add some tests to cover this feature?

**Comment by flosch** [comment]
Could you please add some tests, thanks.

**Comment by gbts** [comment]
Added tests, some comments & tried to make the code handle all cases with negative bounds as close to Python slicing as possible. That also fixed an existing test case for [2,1] which should have been returning an empty slice

**Comment by flosch** [comment]
Thanks for your contribution!

**Pull request merged**
