### PR TITLE
Fix for Issue #297

### PR DESCRIPTION
**Pull request by deroshkin**
fixed a bug that caused the wordwrap filter to miscalculate line count

### CODE REVIEW

**Comment by flosch** [comment]
Can you please add a test demonstrating the (now fixed) bug, thank you.

**Comment by deroshkin** [comment]
Added test, it's a setup that both gave an error before and also tests the actual word wrap.

**Comment by lrstanley** [comment]
@flosch anything else needed on this?

**Comment by flosch** [comment]
Thanks for your contribution!

**Pull request merged**
