### PR TITLE
add the ability to set variables through inline definitions

### PR DESCRIPTION
**Pull request by karakanb**
this PR is an attempt to add support for inline variables into pongo2, allowing templates to be used for cases where there's a predefined set of values to be looped through.

this is the first time I am touching a parser, so I am not sure if this is the right way to go with it, I'd be interested in getting feedback or I'd be okay if someone would like to take over to finish it.

### CODE REVIEW

**Comment by flosch** [comment]
Hi @karakanb, thanks for your effort. I just need more (spare) time to go through your proposal. Once I went through (will take at least a few weeks), I'll get back to you. Thanks for your patience and understanding!

**Comment by xc** [comment]
This is a nice feature!

1) Would be nice to change slice value. eg. {%set var1[0] = "Hello"%}

2) Would be powerful if it can support map: eg. {%set var1 = {"key1": value, "key2": value2} %} . Some complex templating need creating/modifying map in template.

**Comment by heinwessels** [comment]
This feature will be very useful to me too :)

**Comment by sgielen** [comment]
This would be a really convenient addition for us! Could we perhaps consider merging it with the current feature set, and then implement the additions @xc mentioned in a future PR?

**Pull request merged**
